---
title: "HW 2"
output: github_document
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl) # confirm this is the package he wants

```


## Problem 1

```{r}

# read in Mr. Trash Wheel data excluding the header and note column 
df_trash_data = read_excel("Data/HealthyHarborWaterWheelTotals2018-7-28.xlsx",
                           sheet = "Mr. Trash Wheel",
                           range = cell_cols("A:N"),
                           skip = 1)

# clean names
df_trash_data = df_trash_data %>% 
  janitor::clean_names()

# drop summary rows
df_trash_data = df_trash_data %>% 
  drop_na(dumpster)

# round sports balls field
df_trash_data = df_trash_data %>% 
  mutate(
    sports_balls = round(sports_balls, 0) %>% 
      as.integer()
  )

# read in 2017 precipitation data
df_precipitation_17 = read_excel("Data/HealthyHarborWaterWheelTotals2018-7-28.xlsx",
                                 sheet = "2017 Precipitation",
                                 range = "A2:B14")

# clean names
df_precipitation_17 = df_precipitation_17 %>% 
  janitor::clean_names()

# filter out missing values and add year feature
df_precipitation_17 = df_precipitation_17 %>% 
  drop_na(total) %>% 
  mutate(year = 2017)


# read in 2018 precipitation data
df_precipitation_18 = read_excel("Data/HealthyHarborWaterWheelTotals2018-7-28.xlsx",
                                 sheet = "2018 Precipitation",
                                 range = "A2:B14")

# clean names
df_precipitation_18 = df_precipitation_18 %>% 
  janitor::clean_names()

# filter out missing values and add year feature
df_precipitation_18 = df_precipitation_18 %>% 
  drop_na(total) %>% 
  mutate(year = 2018)


# join the datasets together
df_precipitation = rbind(df_precipitation_17, df_precipitation_18)

# change month values to character names
df_precipitation = df_precipitation %>% 
  mutate(
    month = month.name[month]
  )

```

Write a paragraph about these data; you are encouraged to use inline R. Be sure to note the number of observations in both resulting datasets, and give examples of key variables. For available data, what was the total precipitation in 2018? What was the median number of sports balls in a dumpster in 2017?

```{r}

df_precipitation %>% 
  group_by(year) %>% 
  filter(!(month %in% c("August", 
                        "September", 
                        "October", 
                        "November", 
                        "December"))) %>% 
  summarise(mean(total))

df_precipitation %>% 
  group_by(year) %>% 
  summarise(mean(total))

df_precipitation %>% 
  pivot_wider(names_from = year, values_from = total) %>% 
  mutate(difference = `2018` - `2017`)


```




















